/* ============================================================
   DATA.SQL - USUARIOS CLIENTES API
   PROYECTO MASTERBIKES
   Crea tablas y carga datos iniciales
   ============================================================ */


/* ============================================================
   1. DROP DE TABLAS
   Primero se elimina USUARIO porque depende de TIPO_USUARIO
   ============================================================ */

DROP TABLE usuario CASCADE CONSTRAINTS;

DROP TABLE tipo_usuario CASCADE CONSTRAINTS;


/* ============================================================
   2. CREACIÓN DE TABLA TIPO_USUARIO
   ============================================================ */

CREATE TABLE tipo_usuario (
                              id_tipo      NUMBER GENERATED BY DEFAULT AS IDENTITY,
                              nombre      VARCHAR2(60 CHAR) NOT NULL,
                              descripcion VARCHAR2(200 CHAR),

                              CONSTRAINT pk_tipo_usuario PRIMARY KEY (id_tipo),
                              CONSTRAINT uk_tipo_usuario_nombre UNIQUE (nombre)
);


/* ============================================================
   3. CREACIÓN DE TABLA USUARIO
   ============================================================ */

CREATE TABLE usuario (
                         id_usuario      NUMBER GENERATED BY DEFAULT AS IDENTITY,
                         rut             VARCHAR2(9 CHAR) NOT NULL,
                         nombres         VARCHAR2(100 CHAR) NOT NULL,
                         apellidos       VARCHAR2(100 CHAR) NOT NULL,
                         correo          VARCHAR2(100 CHAR),
                         password        VARCHAR2(255 CHAR) NOT NULL,
                         telefono        VARCHAR2(20 CHAR),
                         fecha_registro  DATE NOT NULL,
                         activo          CHAR(1) NOT NULL,
                         direccion       VARCHAR2(200 CHAR),
                         id_tipo         NUMBER NOT NULL,
                         id_sucursal     NUMBER,

                         CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
                         CONSTRAINT uk_usuario_rut UNIQUE (rut),
                         CONSTRAINT uk_usuario_correo UNIQUE (correo),

                         CONSTRAINT fk_usuario_tipo_usuario
                             FOREIGN KEY (id_tipo)
                                 REFERENCES tipo_usuario(id_tipo),

                         CONSTRAINT chk_usuario_activo
                             CHECK (activo IN ('S', 'N'))
);


/* ============================================================
   4. INSERT TIPO_USUARIO
   ============================================================ */

INSERT INTO tipo_usuario (
    id_tipo,
    nombre,
    descripcion
) VALUES (
             1,
             'ADMINISTRADOR',
             'Usuario administrador del sistema MasterBikes'
         );

INSERT INTO tipo_usuario (
    id_tipo,
    nombre,
    descripcion
) VALUES (
             2,
             'CLIENTE',
             'Cliente registrado para compra y arriendo de productos'
         );

INSERT INTO tipo_usuario (
    id_tipo,
    nombre,
    descripcion
) VALUES (
             3,
             'VENDEDOR',
             'Usuario encargado de atención y gestión de ventas'
         );


/* ============================================================
   5. INSERT USUARIOS
   ============================================================ */

INSERT INTO usuario (
    id_usuario,
    rut,
    nombres,
    apellidos,
    correo,
    password,
    telefono,
    fecha_registro,
    activo,
    id_tipo,
    id_sucursal
) VALUES (
             102,
             '123456789',
             'Esteban',
             'Varas Hernández',
             'esteban@test.cl',
             'clave123',
             '+56912345678',
             DATE '2026-05-14',
             'S',
             1,
             NULL
         );

INSERT INTO usuario (
    rut,
    nombres,
    apellidos,
    correo,
    password,
    telefono,
    fecha_registro,
    activo,
    id_tipo,
    id_sucursal
) VALUES (
             '112223334',
             'Mario',
             'González Soto',
             'mairo.gonzalez@test.cl',
             'clave123',
             '+56911112222',
             SYSDATE,
             'S',
             2,
             NULL
         );

INSERT INTO usuario (
    rut,
    nombres,
    apellidos,
    correo,
    password,
    telefono,
    fecha_registro,
    activo,
    id_tipo,
    id_sucursal
) VALUES (
             '223334445',
             'Rosa José',
             'Medina Pérez',
             'rosa.medina@test.cl',
             'clave123',
             '+56922223333',
             SYSDATE,
             'S',
             2,
             NULL
         );

INSERT INTO usuario (
    rut,
    nombres,
    apellidos,
    correo,
    password,
    telefono,
    fecha_registro,
    activo,
    id_tipo,
    id_sucursal
) VALUES (
             '334445556',
             'Andrea',
             'Huenumilla Rojas',
             'andrea.huenumilla@test.cl',
             'clave123',
             '+56933334444',
             SYSDATE,
             'S',
             3,
             NULL
         );

COMMIT;