spring:
  application:
    name: api-gateway

server:
  port: 8080

microservicios:
  usuarios-url: ${USUARIOS_SERVICE_URL:http://localhost:8081}
  productos-url: ${PRODUCTOS_SERVICE_URL:http://localhost:8082}