spring.application.name=productos-inventario-api
server.port = 8082

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@admin2_high?TNS_ADMIN=C:/Wallet_ADMIN2
spring.datasource.username=ADMIN
spring.datasource.password=Lenny18211993$
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.level.java.sql=DEBUG

spring.sql.init.mode = always
spring.sql.init.continue-on-error = true
usuarios-clientes-api.url=http://localhost:8081

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html