spring.application.name=productos-inventario-api
server.port = 8082

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@basedatosfullstack_high?TNS_ADMIN=C:/Wallet_BASEDATOSFULLSTACK/Wallet_BASEDATOSFULLSTACK
spring.datasource.username=ADMIN
spring.datasource.password=Maximo26102026.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.level.java.sql=DEBUG

spring.sql.init.mode = always
spring.sql.init.continue-on-error = true
usuarios-clientes-api.url=${USUARIOS_SERVICE_URL:http://localhost:8081}

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html