DROP TABLE producto CASCADE CONSTRAINTS;

DROP TABLE categoria_producto CASCADE CONSTRAINTS;


/* ============================================================
   2. CREACIÓN DE TABLA CATEGORIA_PRODUCTO
   ============================================================ */

CREATE TABLE categoria_producto (
                                    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                    nombre       VARCHAR2(60 CHAR) NOT NULL,
                                    descripcion  VARCHAR2(200 CHAR),

                                    CONSTRAINT pk_categoria_producto PRIMARY KEY (id_categoria),
                                    CONSTRAINT uk_categoria_producto_nombre UNIQUE (nombre)
);


/* ============================================================
   3. CREACIÓN DE TABLA PRODUCTO
   ============================================================ */

CREATE TABLE producto (
                          id_producto           NUMBER GENERATED BY DEFAULT AS IDENTITY,
                          codigo                VARCHAR2(30 CHAR) NOT NULL,
                          nombre                VARCHAR2(120 CHAR) NOT NULL,
                          marca                 VARCHAR2(60 CHAR),
                          modelo                VARCHAR2(60 CHAR),
                          precio_venta          NUMBER(12,2) NOT NULL,
                          precio_arriendo_dia   NUMBER(12,2),
                          deposito_garantia     NUMBER(12,2),
                          disponible_venta      CHAR(1) NOT NULL,
                          disponible_arriendo   CHAR(1) NOT NULL,
                          activo                CHAR(1) NOT NULL,
                          stock                 NUMBER(6) DEFAULT 0 NOT NULL,
                          id_categoria          NUMBER NOT NULL,

                          CONSTRAINT pk_producto PRIMARY KEY (id_producto),
                          CONSTRAINT uk_producto_codigo UNIQUE (codigo),

                          CONSTRAINT fk_producto_categoria
                              FOREIGN KEY (id_categoria)
                                  REFERENCES categoria_producto(id_categoria),

                          CONSTRAINT chk_producto_disponible_venta
                              CHECK (disponible_venta IN ('S', 'N')),

                          CONSTRAINT chk_producto_disponible_arriendo
                              CHECK (disponible_arriendo IN ('S', 'N')),

                          CONSTRAINT chk_producto_activo
                              CHECK (activo IN ('S', 'N')),

                          CONSTRAINT chk_producto_precio_venta
                              CHECK (precio_venta > 0),

                          CONSTRAINT chk_producto_precio_arriendo
                              CHECK (precio_arriendo_dia IS NULL OR precio_arriendo_dia >= 0),

                          CONSTRAINT chk_producto_deposito
                              CHECK (deposito_garantia IS NULL OR deposito_garantia >= 0)
);


/* ============================================================
   4. INSERT DE CATEGORÍAS
   ============================================================ */

INSERT INTO categoria_producto (
    nombre,
    descripcion
) VALUES (
             'Bicicletas',
             'Bicicletas disponibles para venta y arriendo'
         );

INSERT INTO categoria_producto (
    nombre,
    descripcion
) VALUES (
             'Accesorios',
             'Accesorios para bicicletas y ciclistas'
         );

INSERT INTO categoria_producto (
    nombre,
    descripcion
) VALUES (
             'Repuestos',
             'Repuestos y componentes para mantención de bicicletas'
         );

INSERT INTO categoria_producto (
    nombre,
    descripcion
) VALUES (
             'Herramientas',
             'Herramientas para reparación y mantención de bicicletas'
         );


/* ============================================================
   5. INSERT DE PRODUCTOS
   ============================================================ */

INSERT INTO producto (
    codigo,
    nombre,
    marca,
    modelo,
    precio_venta,
    precio_arriendo_dia,
    deposito_garantia,
    disponible_venta,
    disponible_arriendo,
    activo,
    stock,
    id_categoria
) VALUES (
             'BICI-001',
             'Bicicleta MTB',
             'Trek',
             'Marlin 5',
             549990,
             18000,
             100000,
             'S',
             'S',
             'S',
             10,
             1
         );

INSERT INTO producto (
    codigo,
    nombre,
    marca,
    modelo,
    precio_venta,
    precio_arriendo_dia,
    deposito_garantia,
    disponible_venta,
    disponible_arriendo,
    activo,
    stock,
    id_categoria
) VALUES (
             'BICI-002',
             'Bicicleta Urbana',
             'Oxford',
             'Orion',
             329990,
             12000,
             80000,
             'S',
             'S',
             'S',
             8,
             1
         );

INSERT INTO producto (
    codigo,
    nombre,
    marca,
    modelo,
    precio_venta,
    precio_arriendo_dia,
    deposito_garantia,
    disponible_venta,
    disponible_arriendo,
    activo,
    stock,
    id_categoria
) VALUES (
             'BICI-003',
             'Bicicleta Ruta',
             'Giant',
             'Contend 3',
             699990,
             25000,
             150000,
             'S',
             'S',
             'S',
             5,
             1
         );

INSERT INTO producto (
    codigo,
    nombre,
    marca,
    modelo,
    precio_venta,
    precio_arriendo_dia,
    deposito_garantia,
    disponible_venta,
    disponible_arriendo,
    activo,
    stock,
    id_categoria
) VALUES (
             'CASCO-001',
             'Casco MTB',
             'Giro',
             'Fixture',
             59990,
             NULL,
             NULL,
             'S',
             'N',
             'S',
             20,
             2
         );

INSERT INTO producto (
    codigo,
    nombre,
    marca,
    modelo,
    precio_venta,
    precio_arriendo_dia,
    deposito_garantia,
    disponible_venta,
    disponible_arriendo,
    activo,
    stock,
    id_categoria
) VALUES (
             'LUZ-001',
             'Luz Delantera LED',
             'Knog',
             'Blinder Mini',
             24990,
             NULL,
             NULL,
             'S',
             'N',
             'S',
             15,
             2
         );

INSERT INTO producto (
    codigo,
    nombre,
    marca,
    modelo,
    precio_venta,
    precio_arriendo_dia,
    deposito_garantia,
    disponible_venta,
    disponible_arriendo,
    activo,
    stock,
    id_categoria
) VALUES (
             'REP-001',
             'Cambio Trasero',
             'Shimano',
             'Deore',
             89990,
             NULL,
             NULL,
             'S',
             'N',
             'S',
             12,
             3
         );

INSERT INTO producto (
    codigo,
    nombre,
    marca,
    modelo,
    precio_venta,
    precio_arriendo_dia,
    deposito_garantia,
    disponible_venta,
    disponible_arriendo,
    activo,
    stock,
    id_categoria
) VALUES (
             'REP-002',
             'Cadena 11 velocidades',
             'Shimano',
             'HG601',
             34990,
             NULL,
             NULL,
             'S',
             'N',
             'S',
             25,
             3
         );

INSERT INTO producto (
    codigo,
    nombre,
    marca,
    modelo,
    precio_venta,
    precio_arriendo_dia,
    deposito_garantia,
    disponible_venta,
    disponible_arriendo,
    activo,
    stock,
    id_categoria
) VALUES (
             'HERR-001',
             'Kit de herramientas básico',
             'Park Tool',
             'Home Mechanic',
             79990,
             NULL,
             NULL,
             'S',
             'N',
             'S',
             7,
             4
         );

COMMIT;